name: CI_CD

# Controls when the workflow will run
on:
  create:
    branches: ["main"]
    tags:
      - v*.*.*
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "create new branch" 
